baseURL: "https://jaclarner.github.io/jaclarner/" 
title: Jac M. Larner
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Research
          url: research/
          weight: 2
        - name: Teaching
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Engagmement
          url: engagement/
          weight: 6
        - name: Fun stuff
          url: fun/
          weight: 7

params:
    description: "I am an Assistant Professor of Political Science at Cardiff University's Wales Governance Centre."
    author: Jac M. Larner
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","research","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: <span style="color:770311">Dr Jac M. Larner</span>
          subtitle: "Croeso! Welcome! I'm Jac and I'm an Assistant Professor of Political Science at Cardiff University. I am a Co-Investigator on the Economic and Social Research Council (ESRC) funded Welsh Election Study, and a research fellow on the ESRC funded Scottish Election Study.<br><br>
    
    My research uses a political psychology framework and survey data to answer questions about political behaviour and public opinion. Some of this work has been published in peer-reviewed journals including the *British Journal of Political Science*, *Political Psychology*, *Political Behavior*, and the *Journal of Experimental Research*. I'm a firm believer in the importance of making this research accessible to the public and I regularly contribute analysis on Welsh and UK politics .<br><br>
    
    At Cardiff I am affiliated with the Wales Governance Centre, and through my work with the Scottish Election Study I am a Research Fellow at the University of Edinburgh. Previously, I was a Fulbright Fellow at the University of Michigan's Center for Political Studies (Institute for Social Research). My research is funded by the Economic and Social Research Council and the British Academy/Leverhulme Trust."
          imageUrl: "BBC_Jac copy.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Teaching
              url: courses/
            - name: Data
              url: data/
            - name: Books
              url: books/
            - name: Engagement
              url: engagement/
              - name: Fun stuff
              url: fun/
              
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:larnerJM@cardiff.ac.uk
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=vDQQjSwAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/jaclarner
        - name: YouTube
          url: https://www.youtube.com/watch?v=7CMXfpiWfso&t=7s
        - name: Bluesky
          url: https://bsky.app/profile/jaclarner.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jac M. Larner"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
