baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Jac M. Larner
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "I am an Assistant Professor of Political Science at Cardiff University's Wales Governance Centre"
    author: Jac M. Larner
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
    enabled: true
    title: <span style="color:770311">Dr Jac M. Larner</span>
    subtitle:
    "Croeso! Welcome! I am an Assistant Professor of Political Science at Cardiff University and I am a Co-Investigator on the Economic and Social Research Council funded Welsh Election Study, and a research fellow on the ESRC funded Scottish Election Study. My research uses a political psychology framework and survey data to answer questions about political behaviour and public opinion. Some of this work has been published in peer-reviewed journals including the *British Journal of Political Science*, *Political Psychology*, *Political Behavior*, and the *Journal of Experimental Research*. In 2022 I published a book with colleagues on the 2014 Scottish Independence Referendum. I'm a firm believer in the importance of making this research accessible to the public, and am a frequent media contributor. At Cardiff I am affiliated with the Wales Governance Centre, and through my work with the Scottish Election Study I am a Research Fellow at the University of Edinburgh. Previously, I was a Fulbright Fellow at the University of Michigan's Center for Political Studies (Institute for Social Research). My research is funded by the Economic and Social Research Council and the British Academy/Leverhulme Trust."
  imageUrl: "BBC_Jac copy.png"
  imageWidth: 160
  imageHeight: 160
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: Data
              url: data/
            - name: Books
              url: books/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:moritz.maria.von.igelfeld@gmail.com
        - name: Zoom
          url: https://www.zoom.us/my/igelfeld
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/pmichaillat
        - name: Substack
          url: https://pmichaillat.substack.com
        - name: YouTube
          url: https://www.youtube.com/@alexandermccallsmithoffici9000
        - name: Twitter
          url: https://twitter.com/McCallSmith

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jac M. Larner"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
